<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $quiz->title }} - Exam Paper</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            line-height: 1.6;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
        }
        .exam-title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 10px;
        }
        .exam-info {
            font-size: 14px;
            color: #666;
        }
        .instructions {
            background-color: #f5f5f5;
            padding: 15px;
            margin-bottom: 20px;
            border-left: 4px solid #007bff;
        }
        .question {
            margin-bottom: 25px;
            page-break-inside: avoid;
        }
        .question-number {
            font-weight: bold;
            font-size: 16px;
            margin-bottom: 10px;
        }
        .question-text {
            margin-bottom: 15px;
        }
        .options {
            margin-left: 20px;
        }
        .option {
            margin-bottom: 8px;
        }
        .option-letter {
            font-weight: bold;
            margin-right: 10px;
        }
        .answer-key {
            page-break-before: always;
            margin-top: 40px;
        }
        .answer-key-title {
            font-size: 20px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .answer-item {
            margin-bottom: 10px;
            padding: 5px 0;
        }
        .footer {
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            text-align: center;
            font-size: 12px;
            color: #666;
            border-top: 1px solid #ddd;
            padding: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="exam-title">{{ $quiz->title }}</div>
        <div class="exam-info">
            <div>Date: {{ $examDate }}</div>
            <div>Time Limit: {{ $timeLimit }}</div>
            <div>Total Questions: {{ $totalQuestions }}</div>
        </div>
    </div>

    @if(($includeInstructions ?? true) && $quiz->quiz_description)
    <div class="instructions">
        <strong>Instructions:</strong><br>
        {{ $quiz->quiz_description }}
    </div>
    @endif

    <div class="questions">
        @foreach($questions as $index => $question)
        <div class="question">
            <div class="question-number">Question {{ $index + 1 }}:</div>
            <div class="question-text">{{ $question->title }}</div>
            <div class="options">
                @foreach($question->answers as $answerIndex => $answer)
                <div class="option">
                    <span class="option-letter">{{ chr(65 + $answerIndex) }})</span>
                    {{ $answer->title }}
                </div>
                @endforeach
            </div>
        </div>
        @endforeach
    </div>

    <div class="answer-key">
        <div class="answer-key-title">ANSWER KEY</div>
        @foreach($answerKey as $questionNumber => $correctAnswer)
        <div class="answer-item">
            <strong>Question {{ $questionNumber }}:</strong> {{ $correctAnswer }}
        </div>
        @endforeach
    </div>

    <div class="footer">
        Generated by ExamGenerator.ai - {{ now()->format('d/m/Y H:i') }}
    </div>
</body>
</html>
